version: '3.9'

services:
  api:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db
      - sidekiq
    volumes:
      - .:/app

  db:
    image: postgres:13.3
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  redis:
    image: redis:4.0-alpine

  sidekiq:
    build: .
    command: bundle exec sidekiq
    depends_on:
      - redis
    volumes:
      - .:/app

volumes:
  db-data:
